spaces:
  -
    name: "Backfill"
    order:
      - schedule_counts.json
      - schedule_cursor.json
      - schedule_page_median_95th.json
      - backfill_query_95ths.json
      - backfill_query_medians.json
      - backfill_queue_size.json
      - backfilling_pull_request_records_count.json

accounts:
  com:
    user: mathias@travis-ci.com
    vars:
      app: travis-pro-github-sync
      db_source: travis-pro-production.heroku_postgresql_maroon
      db_name: maroon

  org:
    user: mathias@travis-ci.org
    vars:
      app: travis-github-sync
      db_source: travis-production.heroku_postgresql_white
      db_name: white

