language: ruby
dist: trusty
services:
  - redis-server
  - postgresql
rvm: 2.4.1
before_install:
  - rvm list
before_script:
  - export DB_STRUCTURE_URL=https://raw.githubusercontent.com/travis-ci/travis-migrations/master/db/main/structure.sql
  - createdb travis_test || true
  - curl -fs $DB_STRUCTURE_URL | psql travis_test
script: bundle exec rspec
addons:
  postgresql: "9.6"
